ip:                 "10.1.10.61"
bathy_port:         2210
sensor_frame:       "norbit"
pointcloud_topic:   "/norbit/detections"
startup_settings:
    set_power:      "1"
    set_gate_mode:  "1"
    set_range:      ".5 30"
#    bad_setting:    "doh"

shutdown_settings:
    set_power:      "0"
